// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdQ02RJWpbu-5P59sF82VGsdjq7Du76LQ',
    appId: '1:611805920686:web:d1f1fa489356dca7f81c3f',
    messagingSenderId: '611805920686',
    projectId: 'app-bus-booking-paners',
    authDomain: 'app-bus-booking-paners.firebaseapp.com',
    storageBucket: 'app-bus-booking-paners.firebasestorage.app',
    measurementId: 'G-QM04PYK9Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDue0_L6sNTwJMBnO838rlKBC5AwoUpqqI',
    appId: '1:611805920686:android:7e2132cdb1e49c9af81c3f',
    messagingSenderId: '611805920686',
    projectId: 'app-bus-booking-paners',
    storageBucket: 'app-bus-booking-paners.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIYbi-v9eZHeUv3lQMZAe754D1bsenZtY',
    appId: '1:611805920686:ios:3ea95bb82339ffbaf81c3f',
    messagingSenderId: '611805920686',
    projectId: 'app-bus-booking-paners',
    storageBucket: 'app-bus-booking-paners.firebasestorage.app',
    iosBundleId: 'com.example.busBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIYbi-v9eZHeUv3lQMZAe754D1bsenZtY',
    appId: '1:611805920686:ios:3ea95bb82339ffbaf81c3f',
    messagingSenderId: '611805920686',
    projectId: 'app-bus-booking-paners',
    storageBucket: 'app-bus-booking-paners.firebasestorage.app',
    iosBundleId: 'com.example.busBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdQ02RJWpbu-5P59sF82VGsdjq7Du76LQ',
    appId: '1:611805920686:web:cc93ab60bc286178f81c3f',
    messagingSenderId: '611805920686',
    projectId: 'app-bus-booking-paners',
    authDomain: 'app-bus-booking-paners.firebaseapp.com',
    storageBucket: 'app-bus-booking-paners.firebasestorage.app',
    measurementId: 'G-XGKYP311GC',
  );
}
